### ISSUE TITLE
Indiquer que le nom d'utilisateur est obligatoire

### ISSUE THREAD

**Issue by ccocoual** [ZenikaOuest/jmjar-hero#11]
Indiquer qu'il faut un nom d'utilisateur pour pouvoir commencer

**Comment by mmouterde** [comment]
En fait je me suis dit que les joueurs seraient guidé pour y jouer. Que ce ne serait sans doute pas en libre service... du coup j'ai fait l'impasse là dessus. mais en effet ca manque dans l'UX ^^
