### ISSUE TITLE
compter le score

### ISSUE THREAD

**Issue by mmouterde** [ZenikaOuest/jmjar-hero#3]
- définir un moyen de calculer un score (+ bonus ?)

**Comment by ccocoual** [comment]
Dans le délai de 600ms pour jouer la note, récupérer le temps de saisie de la note et définir un score en fonction de la proximité de la saisie avec la position de la note dans le morceau.
Par exemple: 
- précision de 100ms = 120 points
- précision de 200ms = 100 points
- précision de 300ms = 80 points
- précision de 400ms = 60 points
- précision de 500ms = 40 points
- précision de 600ms = 20 points

**Comment by Okazari** [comment]
Classique dans ce genre de jeu, il y a souvent un multiplicateur en fonction des chaînes de réussites. (Mutiplicateur de "combo" qui monte jusqu'à un x5 ?)

**Comment by mmouterde** [comment]
le problème de l'API HTML de mojs c'est qu'il n'y a qu'une seule instance et si l'animation se réactive trop souvent .. l'unique élément deviens vraiment furtif. Il faudrait faire plusieurs instance et les prendre une par une.

Il y avait un problème sur le positionnement du totalScore (résolu)
